/**
 * Reproduce the drift between the deployed circuits and the published fixtures.
 *
 * Two primitives in `circuits/lib/testdata/` do not match what the circuits
 * shipped in `packages/tokens/src/confidential/circuits/` compute. This script
 * shows both, from the fixtures fetched live and from the circuits themselves,
 * so the difference can be checked without taking anyone's word for it.
 *
 * It makes no claim about which side is correct. The fixtures are generated by
 * `nargo test print_fixtures` against the Noir library; the compiled artifacts a
 * client vendors and the verifier deployed on testnet were built earlier. The
 * only assertion here is that the two disagree, and by how much.
 *
 * Run:  node examples/drift.mjs
 */

import {
  ecdh,
  scalarMul,
  pointCoords,
  H,
  poseidonWithDomain,
  spongeSqueeze2,
  encryptAuditorSenderBalance,
  deriveKeys,
  frAdd,
  FR_MODULUS,
} from "stellar-confidential-token-sdk";
import { CircuitProver } from "stellar-confidential-token-sdk";
import { loadCircuit } from "stellar-confidential-token-sdk/node";
import { buildWithdrawWitness } from "stellar-confidential-token-sdk";

const TESTDATA =
  "https://raw.githubusercontent.com/OpenZeppelin/stellar-contracts/main" +
  "/packages/tokens/src/confidential/circuits/lib/testdata";

const hex = (v) => `0x${(typeof v === "bigint" ? v : BigInt(v)).toString(16).padStart(64, "0")}`;

async function fixture(name) {
  const res = await fetch(`${TESTDATA}/${name}.json`);
  if (!res.ok) throw new Error(`could not fetch ${name}.json (${res.status})`);
  return res.json();
}

function rule(title) {
  console.log(`\n${"─".repeat(72)}\n${title}\n${"─".repeat(72)}`);
}

// ── 1 · ecdh ─────────────────────────────────────────────────────────────────
//
// The fixture's own description says the derivation is
// Poseidon2(delta_ecdh, S.x, S.y) with S = s*P, and explains why: absorbing both
// coordinates removes the (P, -P) negation invariance of an x-only extraction.
// The compiled circuits behave as though it is x-only.

rule("1 · ecdh");

const ecdhFix = await fixture("ecdh");
const v1 = ecdhFix.vectors[0];
const S = scalarMul(BigInt(v1.inputs.scalar), H);
const { x: Sx, y: Sy } = pointCoords(S);

console.log(`inputs                 scalar=${v1.inputs.scalar}, point=${v1.inputs.point}`);
console.log(`fixture says           ${hex(v1.output)}`);
console.log(`x-only, (s*P).x        ${hex(ecdh(BigInt(v1.inputs.scalar), H))}`);

// Recover the domain tag the fixture was generated with, rather than assuming
// it: only one small value reproduces the published output.
let deltaEcdh = null;
for (let d = 0n; d <= 64n && deltaEcdh === null; d++) {
  if (poseidonWithDomain(d, [Sx, Sy]) === BigInt(v1.output)) deltaEcdh = d;
}
console.log(
  `Poseidon2(δ, S.x, S.y) ${
    deltaEcdh === null ? "no small δ reproduces it" : `${hex(poseidonWithDomain(deltaEcdh, [Sx, Sy]))}  (δ = ${deltaEcdh})`
  }`,
);
console.log(
  `\n→ the fixture matches the Poseidon2 form; the vendored circuits match x-only.`,
);
if (deltaEcdh !== null) {
  console.log(
    `→ note δ_ecdh = ${deltaEcdh}, which lib.nr's domain table also assigns to selective disclosure.`,
  );
}

// ── 2 · encrypt_auditor_sender_balance ───────────────────────────────────────
//
// The fixture states the formula explicitly:
//   b_tilde_aud_s = v_new + SpongeSqueeze_2(AUDITOR_SENDER, s_a_s, sigma)[1]
// and gives the reason for using the SECOND squeeze: the first is the amount
// slot, left unused so a checkpoint pad can never coincide with an amount pad
// even under (r_e, sigma) reuse.

rule("2 · encrypt_auditor_sender_balance");

const audFix = await fixture("encrypt_auditor_sender_balance");
const v2 = audFix.vectors[0];
const vNew = BigInt(v2.inputs.v_new);
const sAs = BigInt(v2.inputs.s_a_s);
const sigma = BigInt(v2.inputs.sigma);
const AUDITOR_SENDER = 11n;

const squeezes = spongeSqueeze2(AUDITOR_SENDER, sAs, sigma);

console.log(`inputs                 v_new=${v2.inputs.v_new}, s_a_s=${v2.inputs.s_a_s}, sigma=${v2.inputs.sigma}`);
console.log(`fixture says           ${hex(v2.output)}`);
console.log(`v_new + squeeze[0]     ${hex(frAdd(vNew, squeezes[0]))}   ← what the SDK computes`);
console.log(`v_new + squeeze[1]     ${hex(frAdd(vNew, squeezes[1]))}   ← what the fixture documents`);
console.log(
  `\n→ squeeze[1] reproduces the fixture. squeeze[0] is the amount slot the` +
    `\n  fixture says is deliberately left unused.`,
);

// ── 3 · which one the compiled circuit accepts ──────────────────────────────
//
// The above is a disagreement between a fixture and a client. This is the part
// that locates it: prove a withdraw with the first-squeeze form against the
// vendored circuit and see whether the constraint system accepts it.

rule("3 · what the compiled withdraw circuit accepts");

const keys = deriveKeys(0x1234n, 0x2222n);
const witness = buildWithdrawWitness({
  keys,
  v: 1000n,
  r: 7n,
  amount: 250n,
  kAudS: scalarMul(0xabcn, H),
});

// buildWithdrawWitness uses the SDK's encryptAuditorSenderBalance, i.e. the
// first-squeeze form. If the circuit were built from the current library, this
// should fail.
const prover = new CircuitProver(loadCircuit("withdraw"));
let accepted = false;
let why = "";
try {
  accepted = await prover.verify(await prover.prove(witness.inputs));
} catch (e) {
  why = String(e?.message ?? e);
} finally {
  await prover.destroy();
}

console.log(
  accepted
    ? "the vendored withdraw circuit ACCEPTS the first-squeeze form and self-verifies"
    : `the vendored circuit rejected it: ${why}`,
);

console.log(
  `\n→ the vendored artifacts, and the verifier deployed on testnet that was built` +
    `\n  from them, implement the earlier form. A client emitting the form the` +
    `\n  fixtures document would produce proofs that verifier rejects.`,
);

rule("summary");
console.log(
  [
    "15 of the 17 published fixtures reproduce byte-for-byte.",
    "ecdh and encrypt_auditor_sender_balance do not.",
    "In both cases the vendored/deployed circuits implement the earlier form,",
    "and both differences are the ones the fixtures' own descriptions give a",
    "security reason for: negation invariance, and pad reuse.",
    "",
    "No claim is made here about which artifact should change.",
    `Field modulus in use: ${hex(FR_MODULUS)}`,
  ].join("\n"),
);
